version: '3.8'
services:
  cypress:
    build:
      context: .
      args:
        CYPRESS_VERSION: '13.6.6'
    platform: linux/amd64
    entrypoint: /bin/bash
    environment:
      DEBUG: cypress:*:error
    volumes:
      - /cypress/node_modules
      - .:/cypress