version: '3.8'
services:
  cypress:
    build:
      context: .
      args:
        CYPRESS_VERSION: '13.6.4'
        # CHROME_VERSION: '122.0.6261.111-1'
    platform: linux/amd64
    entrypoint: /bin/bash
    environment:
      DEBUG: cypress:*
    volumes:
      - /cypress/node_modules
      - .:/cypress